Compute daily time average in cap for fields that will be written out to mediator auxiliary file
NorESMhub/WW3 pull request #12
Opened 2023-12-05 16:19 UTC by mvertens

# Pull Request Summary
Compute daily time average in cap for fields that will be written out to mediator auxiliary file

## Description
The following fields are now time averaged over a day. Although they are sent to the mediator at every coupling interval the only valid values are those on the day boundary. The averaging needs to be done in the cap because new grid level accumulation and counter module arrays need to be introduced so that accumulation can be unique to ever gridcell (some gridcells have UNDEF values at certain times - and those will not be part of the accumulation).

fd_cesm.yaml:     - standard_name: Sw_ustokes_avg
fd_cesm.yaml:     - standard_name: Sw_vstokes_avg
fd_cesm.yaml:     - standard_name: Sw_hs_avg
fd_cesm.yaml:     - standard_name: Sw_phs0_avg
fd_cesm.yaml:     - standard_name: Sw_phs1_avg
fd_cesm.yaml:     - standard_name: Sw_pdir0_avg
fd_cesm.yaml:     - standard_name: Sw_pdir1_avg
fd_cesm.yaml:     - standard_name: Sw_pTm10_avg
fd_cesm.yaml:     - standard_name: Sw_pTm11_avg
fd_cesm.yaml:     - standard_name: Sw_Tm1_avg
fd_cesm.yaml:     - standard_name: Sw_thm_avg
fd_cesm.yaml:     - standard_name: Sw_thp0_avg
fd_cesm.yaml:     - standard_name: Sw_fp0_avg
fd_cesm.yaml:     - standard_name: Sw_u_avg
fd_cesm.yaml:     - standard_name: Sw_v_avg
fd_cesm.yaml:     - standard_name: Sw_tusx_avg
fd_cesm.yaml:     - standard_name: Sw_tusy_avg

Please also include the following information: 
* Are answer changes expected from this PR? No

### Issue(s) addressed

### Commit Message
Compute daily time average in cap for fields that will be written out to mediator auxiliary file

### Testing
* The test that was done is to run the compset 2000_CAM60_CLM50%SP_CICE_BLOM_MOSART_SGLC_WW3DEV_SESP at the resolution res f19_tn14_wtn14nw and modify user_nl_cpl to have
    **`histaux_wav2med_file1_enabled = .true.`**
* Are the changes covered by regression tests? Not yet
* Have the matrix regression tests been run: Not yet

2023-12-06 15:02 UTC, gold2718 requested changes
Please condense the code (and avoid any potential copy&paste errors) by using a subroutine to compute averages.

2023-12-06 15:02 UTC, gold2718 commented on model/src/wav_import_export.F90
> +          allocate(accum_ustokes_avg(nseal_cpl))
Are these ever deallocated?

2023-12-06 15:02 UTC, gold2718 commented on model/src/wav_import_export.F90
> +       enddo
There is a lot of repeated code in these blocks (above and below). These blocks could be condensed into a single subroutine call taking in the `counter_xxx`, `accum_xxx`, `sw_xxx` arrays along with the name of the field. You might also have to pass in `sec_next`.

2023-12-08 09:59 UTC, gold2718 approved these changes
Looks good now!

2023-12-08 11:17 UTC, mvertens commented on model/src/wav_import_export.F90
> +          allocate(accum_ustokes_avg(nseal_cpl))
No

2023-12-08 11:17 UTC, mvertens commented on model/src/wav_import_export.F90
> +       enddo
Done

2023-12-08 11:17 UTC, merged